#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev add-on get skeemer/wkhtmltox
ARG TARGETARCH
RUN mkdir -p /tmp/wkhtmltox && \
    wget -O /tmp/wkhtmltox/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_${TARGETARCH}.deb && \
    (apt-get update || true) && \
    apt-get install -y /tmp/wkhtmltox/*.deb && \
    rm -rf /tmp/wkhtmltox
